-- Seed profile option sets (generated by scripts/generate-profile-option-seed.mjs)

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('preferred_language', 'Preferred language', 'welcome', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('communication_preference', 'Communication preference', 'welcome', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('account_two_factor', 'Two-factor authentication', 'welcome', 30, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('sex_assigned_at_birth', 'Sex assigned at birth', 'demographics', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('gender_identity', 'Gender identity', 'demographics', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('marital_status', 'Marital status', 'demographics', 30, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('ethnicity', 'Ethnicity (Hispanic/Latino)', 'demographics', 40, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('race', 'Race', 'demographics', 50, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('blood_group', 'Blood group', 'demographics', 60, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('genotype', 'Sickle cell genotype', 'demographics', 70, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('pregnancy_status', 'Pregnancy status', 'demographics', 80, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('breastfeeding_status', 'Breastfeeding', 'demographics', 90, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('menstrual_status', 'Menstrual status', 'demographics', 100, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('menopause_status', 'Menopause status', 'demographics', 110, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('disability_support', 'Disability / accessibility (multi-select in UI)', 'demographics', 120, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('height_unit', 'Height unit', 'vitals', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('weight_unit', 'Weight unit', 'vitals', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_cardiovascular', 'Cardiovascular conditions', 'conditions', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_endocrine', 'Endocrine / metabolic conditions', 'conditions', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_kidney', 'Kidney / urinary conditions', 'conditions', 30, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_respiratory', 'Respiratory conditions', 'conditions', 40, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_neurological', 'Neurological conditions', 'conditions', 50, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_mental_health', 'Mental health conditions', 'conditions', 60, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_gi', 'Gastrointestinal conditions', 'conditions', 70, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_msk', 'Musculoskeletal conditions', 'conditions', 80, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_cancer', 'Cancer / oncology', 'conditions', 90, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_infectious', 'Infectious disease history', 'conditions', 100, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_autoimmune', 'Autoimmune / immune', 'conditions', 110, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_womens_health', 'Women''s health', 'conditions', 120, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_mens_health', 'Men''s health', 'conditions', 130, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('conditions_other', 'Other medical history', 'conditions', 140, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('condition_severity', 'Condition severity', 'conditions', 500, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_diabetes', 'Diabetes medications', 'medications', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_bp', 'Blood pressure medications', 'medications', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_cardiac_lipid', 'Heart / cholesterol', 'medications', 30, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_respiratory', 'Respiratory', 'medications', 40, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_pain', 'Pain / inflammation', 'medications', 50, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_antibiotic', 'Antibiotics / anti-infectives', 'medications', 60, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_mental_health', 'Mental health meds', 'medications', 70, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_gi', 'Gastrointestinal', 'medications', 80, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_hormonal', 'Hormonal / reproductive', 'medications', 90, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('med_class_supplements', 'Supplements / OTC', 'medications', 100, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('medication_route', 'Medication route', 'medications', 500, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('medication_frequency', 'Frequency (examples)', 'medications', 510, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('allergy_type', 'Allergy type', 'allergies', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('allergy_severity', 'Allergy reaction severity', 'allergies', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('family_history_conditions', 'Family history — conditions', 'family_history', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('immunization_vaccines', 'Vaccines', 'immunizations', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('lab_tests', 'Lab tests', 'labs', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('exercise_level', 'Physical activity level', 'lifestyle', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('smoking_status', 'Smoking / tobacco', 'lifestyle', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('alcohol_use', 'Alcohol use', 'lifestyle', 30, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('substance_use', 'Substance use', 'lifestyle', 40, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('diet_pattern', 'Diet pattern', 'lifestyle', 50, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('sleep_quality', 'Sleep quality', 'lifestyle', 60, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('stress_level', 'Stress level', 'lifestyle', 70, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('provider_type_primary', 'Primary care provider types', 'providers', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('provider_type_specialist', 'Specialist types', 'providers', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('provider_type_allied', 'Allied health', 'providers', 30, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('facility_type', 'Facility type', 'providers', 40, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('insurance_coverage_type', 'Insurance coverage type', 'insurance', 10, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('insurance_carrier', 'Insurance carrier (examples)', 'insurance', 20, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('coverage_area', 'Coverage areas', 'insurance', 30, true, null)
on conflict (key) do nothing;

insert into public.profile_option_sets (key, label, group_slug, sort_order, active, description)
values ('emergency_contact_relationship', 'Emergency contact relationship', 'emergency', 10, true, null)
on conflict (key) do nothing;

-- Values
insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('english', 'English', 10),
  ('spanish', 'Spanish', 20),
  ('french', 'French', 30),
  ('mandarin', 'Mandarin', 40),
  ('hindi', 'Hindi', 50),
  ('arabic', 'Arabic', 60),
  ('portuguese', 'Portuguese', 70),
  ('tagalog', 'Tagalog', 80),
  ('vietnamese', 'Vietnamese', 90),
  ('korean', 'Korean', 100),
  ('other', 'Other', 110)
) as v(slug, label, ord)
where s.key = 'preferred_language'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('sms', 'SMS', 10),
  ('email', 'Email', 20),
  ('push', 'Push', 30),
  ('phone-call', 'Phone call', 40)
) as v(slug, label, ord)
where s.key = 'communication_preference'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('not-enabled', 'Not enabled', 10),
  ('sms', 'SMS', 20),
  ('authenticator-app', 'Authenticator app', 30)
) as v(slug, label, ord)
where s.key = 'account_two_factor'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('female', 'Female', 10),
  ('male', 'Male', 20),
  ('intersex', 'Intersex', 30),
  ('prefer-not-to-say', 'Prefer not to say', 40)
) as v(slug, label, ord)
where s.key = 'sex_assigned_at_birth'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('woman', 'Woman', 10),
  ('man', 'Man', 20),
  ('non-binary', 'Non-binary', 30),
  ('prefer-to-self-describe', 'Prefer to self-describe', 40),
  ('prefer-not-to-say', 'Prefer not to say', 50)
) as v(slug, label, ord)
where s.key = 'gender_identity'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('single', 'Single', 10),
  ('married', 'Married', 20),
  ('divorced', 'Divorced', 30),
  ('widowed', 'Widowed', 40),
  ('domestic-partnership', 'Domestic partnership', 50),
  ('prefer-not-to-say', 'Prefer not to say', 60)
) as v(slug, label, ord)
where s.key = 'marital_status'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('hispanic-or-latino', 'Hispanic or Latino', 10),
  ('not-hispanic-or-latino', 'Not Hispanic or Latino', 20),
  ('prefer-not-to-say', 'Prefer not to say', 30)
) as v(slug, label, ord)
where s.key = 'ethnicity'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('american-indian-or-alaska-native', 'American Indian or Alaska Native', 10),
  ('asian', 'Asian', 20),
  ('black-or-african-american', 'Black or African American', 30),
  ('native-hawaiian-or-pacific-islander', 'Native Hawaiian or Pacific Islander', 40),
  ('white', 'White', 50),
  ('more-than-one-race', 'More than one race', 60),
  ('prefer-not-to-say', 'Prefer not to say', 70)
) as v(slug, label, ord)
where s.key = 'race'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('a', 'A+', 10),
  ('a', 'A-', 20),
  ('b', 'B+', 30),
  ('b', 'B-', 40),
  ('ab', 'AB+', 50),
  ('ab', 'AB-', 60),
  ('o', 'O+', 70),
  ('o', 'O-', 80),
  ('unknown', 'Unknown', 90)
) as v(slug, label, ord)
where s.key = 'blood_group'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('aa', 'AA', 10),
  ('as', 'AS', 20),
  ('ss', 'SS', 30),
  ('ac', 'AC', 40),
  ('sc', 'SC', 50),
  ('unknown', 'Unknown', 60)
) as v(slug, label, ord)
where s.key = 'genotype'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('not-pregnant', 'Not pregnant', 10),
  ('pregnant', 'Pregnant', 20),
  ('unknown', 'Unknown', 30),
  ('not-applicable', 'Not applicable', 40)
) as v(slug, label, ord)
where s.key = 'pregnancy_status'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('yes', 'Yes', 10),
  ('no', 'No', 20),
  ('unknown', 'Unknown', 30),
  ('not-applicable', 'Not applicable', 40)
) as v(slug, label, ord)
where s.key = 'breastfeeding_status'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('regular', 'Regular', 10),
  ('irregular', 'Irregular', 20),
  ('amenorrhea', 'Amenorrhea', 30),
  ('not-applicable', 'Not applicable', 40)
) as v(slug, label, ord)
where s.key = 'menstrual_status'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('pre-menopause', 'Pre-menopause', 10),
  ('peri-menopause', 'Peri-menopause', 20),
  ('post-menopause', 'Post-menopause', 30),
  ('not-applicable', 'Not applicable', 40)
) as v(slug, label, ord)
where s.key = 'menopause_status'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('vision-impairment', 'Vision impairment', 10),
  ('hearing-impairment', 'Hearing impairment', 20),
  ('mobility-limitation', 'Mobility limitation', 30),
  ('speech-impairment', 'Speech impairment', 40),
  ('cognitive-support-needs', 'Cognitive support needs', 50),
  ('none', 'None', 60)
) as v(slug, label, ord)
where s.key = 'disability_support'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('cm', 'cm', 10),
  ('ft-in', 'ft-in', 20)
) as v(slug, label, ord)
where s.key = 'height_unit'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('kg', 'kg', 10),
  ('lb', 'lb', 20)
) as v(slug, label, ord)
where s.key = 'weight_unit'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('hypertension', 'Hypertension', 10),
  ('heart-failure', 'Heart failure', 20),
  ('coronary-artery-disease', 'Coronary artery disease', 30),
  ('arrhythmia', 'Arrhythmia', 40),
  ('stroke-history', 'Stroke history', 50),
  ('peripheral-vascular-disease', 'Peripheral vascular disease', 60),
  ('high-cholesterol', 'High cholesterol', 70)
) as v(slug, label, ord)
where s.key = 'conditions_cardiovascular'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('type-1-diabetes', 'Type 1 diabetes', 10),
  ('type-2-diabetes', 'Type 2 diabetes', 20),
  ('prediabetes', 'Prediabetes', 30),
  ('thyroid-disorders', 'Thyroid disorders', 40),
  ('obesity', 'Obesity', 50),
  ('metabolic-syndrome', 'Metabolic syndrome', 60),
  ('gout', 'Gout', 70)
) as v(slug, label, ord)
where s.key = 'conditions_endocrine'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('chronic-kidney-disease', 'Chronic kidney disease', 10),
  ('kidney-stones', 'Kidney stones', 20),
  ('nephrotic-syndrome', 'Nephrotic syndrome', 30),
  ('urinary-tract-disorders', 'Urinary tract disorders', 40),
  ('proteinuria', 'Proteinuria', 50),
  ('dialysis-history', 'Dialysis history', 60)
) as v(slug, label, ord)
where s.key = 'conditions_kidney'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('asthma', 'Asthma', 10),
  ('copd', 'COPD', 20),
  ('tuberculosis-history', 'Tuberculosis history', 30),
  ('sleep-apnea', 'Sleep apnea', 40),
  ('chronic-bronchitis', 'Chronic bronchitis', 50),
  ('pulmonary-fibrosis', 'Pulmonary fibrosis', 60)
) as v(slug, label, ord)
where s.key = 'conditions_respiratory'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('epilepsy', 'Epilepsy', 10),
  ('migraine', 'Migraine', 20),
  ('parkinson-s-disease', 'Parkinson''s disease', 30),
  ('multiple-sclerosis', 'Multiple sclerosis', 40),
  ('dementia', 'Dementia', 50),
  ('neuropathy', 'Neuropathy', 60)
) as v(slug, label, ord)
where s.key = 'conditions_neurological'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('anxiety-disorder', 'Anxiety disorder', 10),
  ('depression', 'Depression', 20),
  ('bipolar-disorder', 'Bipolar disorder', 30),
  ('ptsd', 'PTSD', 40),
  ('adhd', 'ADHD', 50),
  ('schizophrenia', 'Schizophrenia', 60),
  ('substance-use-disorder', 'Substance use disorder', 70)
) as v(slug, label, ord)
where s.key = 'conditions_mental_health'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('peptic-ulcer-disease', 'Peptic ulcer disease', 10),
  ('gerd', 'GERD', 20),
  ('ibs', 'IBS', 30),
  ('crohn-s-disease', 'Crohn''s disease', 40),
  ('ulcerative-colitis', 'Ulcerative colitis', 50),
  ('liver-disease', 'Liver disease', 60),
  ('hepatitis', 'Hepatitis', 70)
) as v(slug, label, ord)
where s.key = 'conditions_gi'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('arthritis', 'Arthritis', 10),
  ('osteoporosis', 'Osteoporosis', 20),
  ('chronic-back-pain', 'Chronic back pain', 30),
  ('fibromyalgia', 'Fibromyalgia', 40),
  ('lupus', 'Lupus', 50),
  ('joint-replacement-history', 'Joint replacement history', 60)
) as v(slug, label, ord)
where s.key = 'conditions_msk'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('breast-cancer', 'Breast cancer', 10),
  ('prostate-cancer', 'Prostate cancer', 20),
  ('cervical-cancer', 'Cervical cancer', 30),
  ('colon-cancer', 'Colon cancer', 40),
  ('leukemia', 'Leukemia', 50),
  ('lymphoma', 'Lymphoma', 60),
  ('cancer-survivor', 'Cancer survivor', 70)
) as v(slug, label, ord)
where s.key = 'conditions_cancer'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('hiv', 'HIV', 10),
  ('hepatitis-b', 'Hepatitis B', 20),
  ('hepatitis-c', 'Hepatitis C', 30),
  ('malaria-recurrence', 'Malaria recurrence', 40),
  ('tuberculosis', 'Tuberculosis', 50),
  ('covid-19-complications', 'COVID-19 complications', 60)
) as v(slug, label, ord)
where s.key = 'conditions_infectious'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('rheumatoid-arthritis', 'Rheumatoid arthritis', 10),
  ('psoriasis', 'Psoriasis', 20),
  ('sickle-cell-disease', 'Sickle cell disease', 30),
  ('immunodeficiency', 'Immunodeficiency', 40),
  ('celiac-disease', 'Celiac disease', 50)
) as v(slug, label, ord)
where s.key = 'conditions_autoimmune'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('pcos', 'PCOS', 10),
  ('endometriosis', 'Endometriosis', 20),
  ('fibroids', 'Fibroids', 30),
  ('pregnancy-induced-hypertension', 'Pregnancy-induced hypertension', 40),
  ('gestational-diabetes-history', 'Gestational diabetes history', 50)
) as v(slug, label, ord)
where s.key = 'conditions_womens_health'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('benign-prostatic-hyperplasia', 'Benign prostatic hyperplasia', 10),
  ('erectile-dysfunction', 'Erectile dysfunction', 20),
  ('prostatitis', 'Prostatitis', 30),
  ('testosterone-deficiency', 'Testosterone deficiency', 40)
) as v(slug, label, ord)
where s.key = 'conditions_mens_health'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('organ-transplant', 'Organ transplant', 10),
  ('blood-transfusion-history', 'Blood transfusion history', 20),
  ('frequent-hospitalization', 'Frequent hospitalization', 30),
  ('chronic-pain-disorder', 'Chronic pain disorder', 40),
  ('rare-disease', 'Rare disease', 50)
) as v(slug, label, ord)
where s.key = 'conditions_other'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('mild', 'Mild', 10),
  ('moderate', 'Moderate', 20),
  ('severe', 'Severe', 30),
  ('unknown', 'Unknown', 40)
) as v(slug, label, ord)
where s.key = 'condition_severity'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('metformin', 'Metformin', 10),
  ('insulin', 'Insulin', 20),
  ('empagliflozin', 'Empagliflozin', 30),
  ('dapagliflozin', 'Dapagliflozin', 40),
  ('sitagliptin', 'Sitagliptin', 50),
  ('sulfonylureas', 'Sulfonylureas', 60)
) as v(slug, label, ord)
where s.key = 'med_class_diabetes'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('labetalol', 'Labetalol', 10),
  ('amlodipine', 'Amlodipine', 20),
  ('losartan', 'Losartan', 30),
  ('lisinopril', 'Lisinopril', 40),
  ('hydrochlorothiazide', 'Hydrochlorothiazide', 50),
  ('atenolol', 'Atenolol', 60)
) as v(slug, label, ord)
where s.key = 'med_class_bp'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('atorvastatin', 'Atorvastatin', 10),
  ('simvastatin', 'Simvastatin', 20),
  ('aspirin', 'Aspirin', 30),
  ('clopidogrel', 'Clopidogrel', 40),
  ('furosemide', 'Furosemide', 50),
  ('spironolactone', 'Spironolactone', 60),
  ('warfarin', 'Warfarin', 70)
) as v(slug, label, ord)
where s.key = 'med_class_cardiac_lipid'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('salbutamol', 'Salbutamol', 10),
  ('budesonide', 'Budesonide', 20),
  ('montelukast', 'Montelukast', 30),
  ('prednisolone', 'Prednisolone', 40),
  ('inhaled-corticosteroids', 'Inhaled corticosteroids', 50)
) as v(slug, label, ord)
where s.key = 'med_class_respiratory'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('paracetamol', 'Paracetamol', 10),
  ('ibuprofen', 'Ibuprofen', 20),
  ('diclofenac', 'Diclofenac', 30),
  ('tramadol', 'Tramadol', 40),
  ('naproxen', 'Naproxen', 50)
) as v(slug, label, ord)
where s.key = 'med_class_pain'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('amoxicillin', 'Amoxicillin', 10),
  ('azithromycin', 'Azithromycin', 20),
  ('ciprofloxacin', 'Ciprofloxacin', 30),
  ('metronidazole', 'Metronidazole', 40),
  ('antifungals', 'Antifungals', 50),
  ('antivirals', 'Antivirals', 60)
) as v(slug, label, ord)
where s.key = 'med_class_antibiotic'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('sertraline', 'Sertraline', 10),
  ('fluoxetine', 'Fluoxetine', 20),
  ('amitriptyline', 'Amitriptyline', 30),
  ('diazepam', 'Diazepam', 40),
  ('antipsychotics', 'Antipsychotics', 50),
  ('mood-stabilizers', 'Mood stabilizers', 60)
) as v(slug, label, ord)
where s.key = 'med_class_mental_health'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('omeprazole', 'Omeprazole', 10),
  ('antacids', 'Antacids', 20),
  ('laxatives', 'Laxatives', 30),
  ('anti-diarrheals', 'Anti-diarrheals', 40)
) as v(slug, label, ord)
where s.key = 'med_class_gi'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('oral-contraceptives', 'Oral contraceptives', 10),
  ('hrt', 'HRT', 20),
  ('fertility-medication', 'Fertility medication', 30),
  ('thyroid-hormone', 'Thyroid hormone', 40)
) as v(slug, label, ord)
where s.key = 'med_class_hormonal'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('iron', 'Iron', 10),
  ('vitamin-d', 'Vitamin D', 20),
  ('calcium', 'Calcium', 30),
  ('multivitamins', 'Multivitamins', 40),
  ('herbal', 'Herbal', 50)
) as v(slug, label, ord)
where s.key = 'med_class_supplements'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('oral', 'Oral', 10),
  ('iv', 'IV', 20),
  ('subcutaneous', 'Subcutaneous', 30),
  ('topical', 'Topical', 40),
  ('inhaled', 'Inhaled', 50),
  ('other', 'Other', 60)
) as v(slug, label, ord)
where s.key = 'medication_route'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('once-daily', 'Once daily', 10),
  ('twice-daily', 'Twice daily', 20),
  ('three-times-daily', 'Three times daily', 30),
  ('as-needed', 'As needed', 40),
  ('weekly', 'Weekly', 50),
  ('other', 'Other', 60)
) as v(slug, label, ord)
where s.key = 'medication_frequency'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('drug', 'Drug', 10),
  ('food', 'Food', 20),
  ('environmental', 'Environmental', 30),
  ('other', 'Other', 40)
) as v(slug, label, ord)
where s.key = 'allergy_type'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('mild', 'Mild', 10),
  ('moderate', 'Moderate', 20),
  ('severe', 'Severe', 30),
  ('unknown', 'Unknown', 40)
) as v(slug, label, ord)
where s.key = 'allergy_severity'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('diabetes', 'Diabetes', 10),
  ('hypertension', 'Hypertension', 20),
  ('cancer', 'Cancer', 30),
  ('kidney-disease', 'Kidney disease', 40),
  ('heart-disease', 'Heart disease', 50),
  ('stroke', 'Stroke', 60),
  ('sickle-cell-disease', 'Sickle cell disease', 70),
  ('mental-health-conditions', 'Mental health conditions', 80)
) as v(slug, label, ord)
where s.key = 'family_history_conditions'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('covid-19', 'COVID-19', 10),
  ('tetanus', 'Tetanus', 20),
  ('hepatitis-b', 'Hepatitis B', 30),
  ('influenza', 'Influenza', 40),
  ('mmr', 'MMR', 50),
  ('varicella', 'Varicella', 60),
  ('polio', 'Polio', 70),
  ('other', 'Other', 80)
) as v(slug, label, ord)
where s.key = 'immunization_vaccines'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('blood-glucose', 'Blood glucose', 10),
  ('hba1c', 'HbA1c', 20),
  ('creatinine', 'Creatinine', 30),
  ('egfr', 'eGFR', 40),
  ('lipid-profile', 'Lipid profile', 50),
  ('urinalysis', 'Urinalysis', 60),
  ('liver-panel', 'Liver panel', 70),
  ('tsh', 'TSH', 80),
  ('other', 'Other', 90)
) as v(slug, label, ord)
where s.key = 'lab_tests'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('none', 'None', 10),
  ('light', 'Light', 20),
  ('moderate', 'Moderate', 30),
  ('intense', 'Intense', 40),
  ('prefer-not-to-say', 'Prefer not to say', 50)
) as v(slug, label, ord)
where s.key = 'exercise_level'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('never-smoked', 'Never smoked', 10),
  ('former-smoker', 'Former smoker', 20),
  ('current-smoker', 'Current smoker', 30),
  ('occasionally', 'Occasionally', 40),
  ('vaping', 'Vaping', 50),
  ('smokeless-tobacco', 'Smokeless tobacco', 60),
  ('prefer-not-to-say', 'Prefer not to say', 70)
) as v(slug, label, ord)
where s.key = 'smoking_status'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('never', 'Never', 10),
  ('occasionally', 'Occasionally', 20),
  ('weekly', 'Weekly', 30),
  ('daily', 'Daily', 40),
  ('heavy-use', 'Heavy use', 50),
  ('prefer-not-to-say', 'Prefer not to say', 60)
) as v(slug, label, ord)
where s.key = 'alcohol_use'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('none', 'None', 10),
  ('recreational-drugs', 'Recreational drugs', 20),
  ('prescription-misuse', 'Prescription misuse', 30),
  ('cannabis', 'Cannabis', 40),
  ('opioid-use', 'Opioid use', 50),
  ('other', 'Other', 60),
  ('prefer-not-to-say', 'Prefer not to say', 70)
) as v(slug, label, ord)
where s.key = 'substance_use'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('no-restriction', 'No restriction', 10),
  ('vegetarian', 'Vegetarian', 20),
  ('vegan', 'Vegan', 30),
  ('low-salt', 'Low salt', 40),
  ('low-sugar', 'Low sugar', 50),
  ('renal-diet', 'Renal diet', 60),
  ('high-protein', 'High protein', 70),
  ('other', 'Other', 80)
) as v(slug, label, ord)
where s.key = 'diet_pattern'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('poor', 'Poor', 10),
  ('fair', 'Fair', 20),
  ('good', 'Good', 30),
  ('excellent', 'Excellent', 40)
) as v(slug, label, ord)
where s.key = 'sleep_quality'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('low', 'Low', 10),
  ('medium', 'Medium', 20),
  ('high', 'High', 30)
) as v(slug, label, ord)
where s.key = 'stress_level'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('family-physician', 'Family physician', 10),
  ('general-practitioner', 'General practitioner', 20),
  ('internist', 'Internist', 30),
  ('pediatrician', 'Pediatrician', 40)
) as v(slug, label, ord)
where s.key = 'provider_type_primary'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('nephrologist', 'Nephrologist', 10),
  ('cardiologist', 'Cardiologist', 20),
  ('endocrinologist', 'Endocrinologist', 30),
  ('neurologist', 'Neurologist', 40),
  ('pulmonologist', 'Pulmonologist', 50),
  ('gastroenterologist', 'Gastroenterologist', 60),
  ('oncologist', 'Oncologist', 70),
  ('psychiatrist', 'Psychiatrist', 80),
  ('dermatologist', 'Dermatologist', 90),
  ('orthopedic', 'Orthopedic', 100),
  ('gynecologist', 'Gynecologist', 110),
  ('urologist', 'Urologist', 120),
  ('other', 'Other', 130)
) as v(slug, label, ord)
where s.key = 'provider_type_specialist'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('pharmacist', 'Pharmacist', 10),
  ('physiotherapist', 'Physiotherapist', 20),
  ('dietitian', 'Dietitian', 30),
  ('psychologist', 'Psychologist', 40),
  ('occupational-therapist', 'Occupational therapist', 50),
  ('speech-therapist', 'Speech therapist', 60),
  ('other', 'Other', 70)
) as v(slug, label, ord)
where s.key = 'provider_type_allied'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('hospital', 'Hospital', 10),
  ('clinic', 'Clinic', 20),
  ('laboratory', 'Laboratory', 30),
  ('imaging-center', 'Imaging center', 40),
  ('dialysis-center', 'Dialysis center', 50),
  ('urgent-care', 'Urgent care', 60),
  ('other', 'Other', 70)
) as v(slug, label, ord)
where s.key = 'facility_type'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('private-insurance', 'Private insurance', 10),
  ('employer-sponsored', 'Employer-sponsored', 20),
  ('government-insurance', 'Government insurance', 30),
  ('medicaid', 'Medicaid', 40),
  ('medicare', 'Medicare', 50),
  ('hmo', 'HMO', 60),
  ('ppo', 'PPO', 70),
  ('epo', 'EPO', 80),
  ('pos', 'POS', 90),
  ('self-pay-uninsured', 'Self-pay / uninsured', 100)
) as v(slug, label, ord)
where s.key = 'insurance_coverage_type'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('blue-cross-blue-shield', 'Blue Cross Blue Shield', 10),
  ('aetna', 'Aetna', 20),
  ('cigna', 'Cigna', 30),
  ('unitedhealthcare', 'UnitedHealthcare', 40),
  ('humana', 'Humana', 50),
  ('kaiser-permanente', 'Kaiser Permanente', 60),
  ('regional-local-plan', 'Regional / local plan', 70),
  ('other', 'Other', 80)
) as v(slug, label, ord)
where s.key = 'insurance_carrier'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('primary-insurance', 'Primary insurance', 10),
  ('secondary-insurance', 'Secondary insurance', 20),
  ('prescription', 'Prescription', 30),
  ('dental', 'Dental', 40),
  ('vision', 'Vision', 50),
  ('specialist', 'Specialist', 60),
  ('lab', 'Lab', 70),
  ('emergency', 'Emergency', 80)
) as v(slug, label, ord)
where s.key = 'coverage_area'
on conflict (set_id, slug) do nothing;

insert into public.profile_option_values (set_id, slug, label, sort_order, active)
select s.id, v.slug, v.label, v.ord, true
from public.profile_option_sets s
cross join (values
  ('parent', 'Parent', 10),
  ('spouse', 'Spouse', 20),
  ('sibling', 'Sibling', 30),
  ('friend', 'Friend', 40),
  ('guardian', 'Guardian', 50),
  ('partner', 'Partner', 60),
  ('other', 'Other', 70)
) as v(slug, label, ord)
where s.key = 'emergency_contact_relationship'
on conflict (set_id, slug) do nothing;

